# Generated by Django 6.0 on 2025-12-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_publication_remove_book_author_article_delete_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Publications',
            new_name='publications',
        ),
    ]
